### ISSUE TITLE
Runing interactive graph in Kaggle Notebook

### ISSUE THREAD

**Issue by lcrmorin** [Coding-with-Adam/Dash-by-Plotly#13]
I see your code in : https://github.com/Coding-with-Adam/Dash-by-Plotly/blob/master/Deploy_App_to_Web/Kaggle-GGL-Collab/Dash-on-Kaggle.ipynb 
It is really helpfull as only one of the solution that work on kaggle. However I have a hard time making a simpler thing. That is to make it work directly in kaggle or locally in a notebook (i.e. not building an app but having the interactive graph directly in the notebook). Any idea on how to do that ? use plotly only ?

**Comment by Coding-with-Adam** [comment]
Do you mean Jupyter notebook?

Adam SchroederOwnerCharming Data LLC 118 E 124th ST #1808, New York, New York 10035   My Pronouns: He, him, his ¡Hablo español! 
            
            
            
            
                
                    On Wed, Oct 06, 2021, 11:57 am lcrmorin ***@***.***> wrote:
                    
                
                
                    
I see your code in : https://github.com/Coding-with-Adam/Dash-by-Plotly/blob/master/Deploy_App_to_Web/Kaggle-GGL-Collab/Dash-on-Kaggle.ipynb
It is really helpfull as only one of the solution that work on kaggle. However I have a hard time making a simpler thing. That is to make it work directly in kaggle or locally in a notebook (i.e. not building an app but having the interactive graph directly in the notebook). Any idea on how to do that ? use plotly only ?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Coding-with-Adam/Dash-by-Plotly/issues/13",
"url": "https://github.com/Coding-with-Adam/Dash-by-Plotly/issues/13",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
