### ISSUE TITLE
String formatting question

### ISSUE THREAD

**Issue by hughjward** [Coding-with-Adam/Dash-by-Plotly#9]
Hi, 

Is there a specific reason you use % string formatting here, whereas in line 70 you use f-string?

https://github.com/Coding-with-Adam/Dash-by-Plotly/blob/3fa90ac90306cf04c4f517e402bf3031265f2bda/Dash_More_Advanced_Shit/Dash_Labs/short_app.py#L64

https://github.com/Coding-with-Adam/Dash-by-Plotly/blob/3fa90ac90306cf04c4f517e402bf3031265f2bda/Dash_More_Advanced_Shit/Dash_Labs/short_app.py#L70

**Comment by Coding-with-Adam** [comment]
No. Not really

Adam SchroederOwnerCharming Data LLC 118 E 124th ST #1808, New York, New York 10035   My Pronouns: He, him, his ¡Hablo español! 
            
            
            
            
                
                    On Tue, Aug 24, 2021, 10:17 am Hugh Ward ***@***.***> wrote:
                    
                
                
                    
Hi,
Is there a specific reason you use % string formatting here, whereas in line 70 you use f-string?
https://github.com/Coding-with-Adam/Dash-by-Plotly/blob/3fa90ac90306cf04c4f517e402bf3031265f2bda/Dash_More_Advanced_Shit/Dash_Labs/short_app.py#L64
https://github.com/Coding-with-Adam/Dash-by-Plotly/blob/3fa90ac90306cf04c4f517e402bf3031265f2bda/Dash_More_Advanced_Shit/Dash_Labs/short_app.py#L70

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/Coding-with-Adam/Dash-by-Plotly/issues/9",
"url": "https://github.com/Coding-with-Adam/Dash-by-Plotly/issues/9",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
